module Test {
  fun test : Promise(Void) {
    next { age: 30 }
  }
}

component Main {
  fun render : Html {
    let test =
      Test.test()

    <div/>
  }
}
--------------------------------------------------------------------------------
░ ERROR (NEXT_CALL_INVALID_INVOCATION) ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

A next call can only called inside a component, store or provider but you tried
to call it here:

   ┌ errors/next_call_invalid_invocation:3:5
   ├────────────────────────────────────────
  1│ module Test {
  2│   fun test : Promise(Void) {
  3│     next { age: 30 }
   │     ⌃⌃⌃⌃⌃⌃⌃⌃⌃⌃⌃⌃⌃⌃⌃⌃
  4│   }
  5│ }
  6│
  7│ component Main {
